### ISSUE TITLE
Add spec to functions

### ISSUE THREAD

**Issue by gausby** [pavlos/gen_fsm#1]
I would be great if the module had specs like the Elixir :gen_server wrapper.

**Comment by pavlos** [comment]
Hey @gausby, I was planning on writing some specs soon, but if you'd like to do it, I'd gladly accept a PR!

**Comment by gausby** [comment]
I can perhaps give it a go later. I can do specs but I am not always 100% sure that they are correct :)

**Comment by pavlos** [comment]
We'll get it right together

**Comment by gausby** [comment]
I have started working on this, the progress can be followed in #4 Comments are more than welcome.

**Comment by pavlos** [comment]
I'm going to go ahead and close this ticket since we are working on that PR
