### ISSUE TITLE
Create examples folder

### ISSUE THREAD

**Issue by gausby** [pavlos/gen_fsm#11]
We could add an examples folder to the project where we could store examples of state machines. I think the turnstile example, and the [coffee vendor machine example](https://github.com/elixir-lang/elixir/blob/a6f048b3de4a971c15fc8b66397cf2e4597793cb/lib/elixir/lib/gen_fsm/behaviour.ex) could fit in there nicely.

**Comment by pavlos** [comment]
Good call.  I also have an example of an infinite-looping "worker" FSM that responds to interrupts.  I think we should put the examples as test cases maybe?  Or should we just put them up at the top level?

**Comment by gausby** [comment]
The test cases should be very specific and test one thing. Sounds like the interruptible worker should go in the example folder with comments as annotations.

**Comment by pavlos** [comment]
Cool.  Should I have mix exclude the examples when building hex packages so they don't bloat the release?

**Comment by gausby** [comment]
I would say so. No need to have them published to hex.pm
