### ISSUE TITLE
No support for sync_send_event/2

### ISSUE THREAD

**Issue by marceloomens** [pavlos/gen_fsm#17]
I've just ported my code to use `GenFSM.send_sync_event/2` instead of `GenFSM.send_event/2`. At runtime the VM complains that:

```
[error] ** State machine #PID<0.376.0> terminating
...
** Reason for termination = 
** {:"function not exported",
...
```

There seems to be a problem with synchronously executed state machines.

**Comment by gausby** [comment]
I am fairly sure we support `sync_send_event/2`. Did you remember to change your state handling function to the arity-3 version (`action`, `from`, and `state`)? If not try adding `_from` as the second argument.

**Comment by gausby** [comment]
Check out the [turnstile example](https://github.com/pavlos/gen_fsm/blob/master/examples/turnstile/lib/turnstile.ex). I use and handle `sync_send_event/2` a couple of times in there :)

**Comment by gausby** [comment]
I just reread your description...I think that you have misspelled the function. It is `sync_send_event/2`, not `send_sync_event/2`, _sync_ before _send_. Does that solve the issue?

**Comment by pavlos** [comment]
yeah @marceloomens, @gausby is correct - I think you have a typo.  Gonna close this issue, please open another one if you still have a problem
