### ISSUE TITLE
Add `start` and `start_link` functions

### ISSUE THREAD

**Issue by gausby** [pavlos/gen_fsm#3]
Like the Elixir :gen_server wrapper. This could help smoothen out the rough edges when trying to give the process a name via a process registry in Elixir :)

**Comment by pavlos** [comment]
@gausby - working on it ;-)

**Comment by pavlos** [comment]
@gausby done - it's 2am in San Francisco, so I might have screwed something up, but please check it out

**Comment by gausby** [comment]
I haven't played with it, but on the first skim it looked good (not that I am any kind of gen_fsm expert, I just use it occasionally).

And I just returned home to Copenhagen from San Francisco yesterday, so I guess my body thinks that it is 2 am right now!
