### ISSUE TITLE
Convert some of the simple wrapper functions to `defdelegate`s

### ISSUE THREAD

**Issue by gausby** [pavlos/gen_fsm#7]
Some of the public wrapper functions could be converted to `defdelegate`.

**Comment by pavlos** [comment]
:+1: I can do it after we merge the typespec PR, or you can do it if you want to.

**Comment by gausby** [comment]
Yeah, I thought it would be best to do after we merge the stuff from the typespec PR. I don't need to do it, so just go ahead when we merge #4 :)

**Comment by pavlos** [comment]
I'm going to close this issue since we have this PR (https://github.com/pavlos/gen_fsm/pull/8) already in progress

**Comment by gausby** [comment]
It should close automatically if you include a text like "fixes #7" in the merge commit message :)

**Comment by pavlos** [comment]
nice, didn't know that!
